[package]
name = "iced-project"
version = "0.1.0"
authors = ["Adrian Mache"]
edition = "2021"
publish = false

[dependencies]
iced = {version = "0.13.1", features = ["highlighter", "tokio", "debug" ,"advanced"]}
rfd = "0.15.1"
tokio = { version = "1.41.1", features = ["fs"] }





